name: "CI"
on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  # unit tests
  tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn install
      - run: yarn test
    
  coverage:
    name: Jest Code Coverage Report
    uses: ziishaned/jest-reporter-action@0.1.1
    with:
      github-token: ${{ secrets.GITHUB_TOKEN }}
      test-command: "yarn test --coverage"
