name: "CI"
on:
  pull_request:
  push:
    branches:
      - master
      - "releases/*"

jobs:
  tests:
    name: "Unit tests"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - run: yarn install
      - run: yarn test
    
#   coverage:
#     name: Jest Annotations & Coverage
#     runs-on: ubuntu-latest
#     steps:
#       - uses: mattallty/jest-github-action@v1.0.2
#       - env:
#           GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
#       - with: 
#           test-command: "yarn test"

